In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn


In [2]:
df=pd.read_csv('Breast_cancer_data.csv').dropna()
df.head()


mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   diagnosis  
0          0  
1          0  
2          0  
3          0  
4          0

Train the Model

In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
knn=KNeighborsClassifier(n_neighbors=5)

In [12]:
x=df[['mean_radius','mean_texture','mean_perimeter','mean_area','mean_smoothness']]
y=df['diagnosis']
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1)
x_train.head()

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
562        15.22         30.62          103.40      716.9          0.10480
291        14.96         19.10           97.03      687.3          0.08992
16         14.68         20.13           94.74      684.5          0.09867
546        10.32         16.35           65.31      324.9          0.09434
293        11.85         17.46           75.54      432.7          0.08372

In [13]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

Test the Model


In [16]:
y_pred=knn.predict(x_test)
print(y_pred)
print(y_test)

[1 1 1 0 0 0 0 0 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 1 1 1 0
 0 1 1 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0
 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1
 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1]
421    1
47     0
292    1
186    0
414    0
      ..
232    1
413    1
514    0
244    0
415    1
Name: diagnosis, Length: 143, dtype: int64


In [18]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred,y_test))

0.8531468531468531


Use different k values to check

In [20]:
k_array=np.arange(1,20,2)
k_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
for k in k_array:
    knn_try=KNeighborsClassifier(n_neighbors=k)
    knn_try.fit(x_train,y_train)
    ac=accuracy_score(y_test,knn_try.predict(x_test))
    print(k)
    print(ac)

1
0.8671328671328671
3
0.8601398601398601
5
0.8531468531468531
7
0.8741258741258742
9
0.8741258741258742
11
0.8601398601398601
13
0.8601398601398601
15
0.8601398601398601
17
0.8741258741258742
19
0.8741258741258742


In [25]:
knn_7 = KNeighborsClassifier(n_neighbors = 7)
knn_7.fit(x_train, y_train)
y_pred7 = knn_7.predict(x_test)
print(accuracy_score(y_test, y_pred7))

0.8741258741258742


In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred7)

array([[43, 12],
       [ 6, 82]], dtype=int64)

In [27]:
confusion_matrix(y_test,y_pred)

array([[42, 13],
       [ 8, 80]], dtype=int64)

In [28]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred7,average='micro')

0.8741258741258742